"""Functions that simulate dice rolls.

A dice function takes no arguments and returns a number from 1 to n
(inclusive), where n is the number of sides on the dice.

Types of dice:

 -  A fair dice produces each possible outcome with equal probability.
   Two fair dice are already defined, four_sided and six_sided,
   and are generated by the make_fair_dice function.

 -  A test dice is deterministic: it always cycles through a fixed
   sequence of values that are passed as arguments.
   Test dice are generated by the make_test_dice function.
"""

from random import randint

def make_fair_dice(sides):
    """Return a die that returns 1 to SIDES with equal chance."""
    assert type(sides) == int and sides >= 1, 'Illegal value for sides'
    def dice():
        return randint(1,sides)         # 我的理解这里返回一个1到sides之间的随机数.那么整个函数返回一个1到sides之间的随机数.
    return dice                         # 这里定义了一个函数 dice，注意这个dice本身是没有参数的，它的作用是返回一个数字而已并且以某种概率，应该理解为选择某种骰子这个动作；这个make fairdice的 dice 就是1到sides面 之间的随机数

four_sided = make_fair_dice(4)       # four_sided函数相当于randint(1, 4)即从1到4之间，相同概率产生随机数
six_sided = make_fair_dice(6)        # 这里和上述同理，最终的函数相当于randint(1, 6) 从1到6之间，相同概率产生随机数
                                     # 注意这里的两个变量代表两个函数，一个叫做4面筛，一个叫做六面筛子函数
def make_test_dice(*outcomes):
    """Return a die that cycles deterministically through OUTCOMES.     # 这里产生一个dice函数, 是按照参数的顺序依次生成返回值
    # 返回一个确定性地通过OUTCOMES循环的骰子
    >>> dice = make_test_dice(1, 2, 3)
    >>> dice()
    1
    >>> dice()
    2
    >>> dice()
    3
    >>> dice()
    1
    >>> dice()
    2

    This function uses Python syntax/techniques not yet covered in this course.
    The best way to understand it is by reading the documentation and examples.
    """
    assert len(outcomes) > 0, 'You must supply outcomes to make_test_dice'
    for o in outcomes:
        assert type(o) == int and o >= 1, 'Outcome is not a positive integer'
    index = len(outcomes) - 1
    def dice():
        nonlocal index
        index = (index + 1) % len(outcomes)
        return outcomes[index]
    return dice